### ISSUE TITLE
Nondeterministic pipeline error

### ISSUE THREAD

**Issue by lauritzsh** [gleam-lang/gleam#1422]
At least when using [mix_gleam](https://github.com/gleam-lang/mix_gleam), sometimes I experience a type error happening. What's weird is that it's nondeterministic. To test and evaluate my code, I use the following command `Mix.Task.rerun("gleam.compile") && recompile() && :project@ffi@map.get_and_update(%{"a" => "b"}, "a", fn {:some, b} -> {b, b <> "!"} end)`.

Given a module such as `project/ffi/map` with the content

```gleam
import gleam/map.{Map}
import gleam/option.{Option}

pub fn get_and_update(
  map: Map(a, b),
  key: a,
  fun: fn(Option(b)) -> #(c, b),
) -> #(c, Map(a, b)) {
  let #(current_value, new_value) =
    map
    |> map.get(key)
    |> option.from_result
    |> fun

  #(current_value, map.insert(map, key, new_value))
}
```

With just that module above, I can compile 10 times and not see any error. Now if I add any other module, let's say `project/mod` with the following

```gleam
pub fn hello() -> String {
  "world"
}
```

it'll still compile fine. Now if I have an unused variable such as

```gleam
pub fn hello(unused) -> String {
  "world"
}
```

I'll _sometimes_ see an error

```
iex(63)> Mix.Task.rerun("gleam.compile") && recompile() && :project@ffi@map.get_and_update(%{"a" => "b"}, "a", fn {:some, b} -> {b, b <> "!"} end)
Compiling 2 files (.gleam)
error: This function cannot handle the argument sent through the (|>) pipe:
   ┌─ src/project/ffi/map.gleam:12:8
   │
12 │     |> option.from_result
   │        ^^^^^^^^^^^^^^^^^^

The argument is:

    Result(b, Nil)

But (|>) is piping it to a function that expects:

    Result(a, b)



** (MixGleam.Error) Compilation failed
    (mix_gleam 0.3.0) lib/mix/tasks/gleam/compile.ex:167: Mix.Tasks.Gleam.Compile.compile_package/2
    (mix_gleam 0.3.0) lib/mix/tasks/gleam/compile.ex:82: Mix.Tasks.Gleam.Compile.run/1
    (mix 1.12.3) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
```

but other times it'll compile fine and just warn me about the parameter

```
iex(64)> Mix.Task.rerun("gleam.compile") && recompile() && :project@ffi@map.get_and_update(%{"a" => "b"}, "a", fn {:some, b} -> {b, b <> "!"} end)
Compiling 2 files (.gleam)

warning: Unused variable
  ┌─ src/project/ffi/decimal.gleam:1:14
  │
1 │ pub fn hello(unused) -> String {
  │              ^^^^^^ This variable is never used.

Hint: you can ignore it with an underscore: `_unused`.
Compiling 2 files (.erl)
build/dev/erlang/project/build/project@ffi@decimal.erl:7:7: Warning: variable 'Unused' is unused
%    7| hello(Unused) ->
%     |       ^

Compiling 14 files (.ex)
{"b", %{"a" => "b!"}}
```

In my own project, I could have up to three different outcomes without changing any code between runs.

**Comment by lpil** [comment]
Thank you for this very thorough bug report and reproduction, you've got us so much closer to fixing this than we were before. Thank you!

**Comment by lpil** [comment]
This is fixed on main. Thank you for your reproduction, it was very useful!
