### ISSUE TITLE
Bug: JavaScript thenables

### ISSUE THREAD

**Issue by tynanbe** [gleam-lang/gleam#1537]
When dynamically importing any module with a function named `then`, `then` is called when resolving the `Promise`, generally causing the import to fail.

```javascript
> $gleam$option = await import("./build/dev/javascript/gleam_stdlib/dist/gleam/option.mjs");
Uncaught Error: No case clause matched
    at throwError (file://./build/dev/javascript/gleam_stdlib/dist/gleam.mjs:342:15)
    at Module.then (file://./build/dev/javascript/gleam_stdlib/dist/gleam/option.mjs:135:5)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  gleam_error: 'case_no_match',
  module: 'gleam/option',
  line: 201,
  fn: 'then',
  values: [ [Function (anonymous)] ]
}
```

```javascript
> $gleam$result = await import("./build/dev/javascript/gleam_stdlib/dist/gleam/result.mjs");
Uncaught TypeError: result.isOk is not a function
    at Module.then (file://./build/dev/javascript/gleam_stdlib/dist/gleam/result.mjs:96:14)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

See also: https://github.com/devsnek/proposal-symbol-thenable

**Comment by lpil** [comment]
Thank you
