### ISSUE TITLE
Compiling to Erlang with a module named the same as an Erlang module prevents the application from starting

### ISSUE THREAD

**Issue by J3RN** [gleam-lang/gleam#1648]
I have been working on a `logger` module (`src/logger.gleam`) in [J3RN/isup.website](https://github.com/J3RN/isup.website). However, when the module is present and the application is run (with `gleam run`), it produces the following error:
```
{"Kernel pid terminated",application_controller,{undef,[{logger,allow,[notice,application_controller],[]},{application_controller,info_exited,3,[{file,"application_controller.erl"},{line,2119}]},{application_controller,handle_application_started,3,[{file,"application_controller.erl"},{line,1023}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,1120}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,1197}]}]}}
Kernel pid terminated (application_controller) ({undef,[{logger,allow,[notice,application_controller],[]},{application_controller,info_exited,3,[{_},{_}]},{application_controller,handle_application_started,3,[{_},{_}]},{gen_server,try_dispatch,4,[{_},{_}]},{gen_server,handle_msg,6,[{_},{_}]}]})
```

I tried this pattern but with a module named `gen_server` and got a very similar result:
```
,
[],[]],[]},{init,start_in_kernel,5,[]},{init,eval_script,2,[]},{init,do_boot,3,[]}]}],#{error_logger=>#{emulator=>true,tag=>error},gl=><0.0.0>,pid=><0.9.0>,time=>1653444767013051}}
init terminating in do_boot ({undef,[{gen_server,start_link,[{_},logger_server,[_],[_]],[]},{init,start_in_kernel,5,[]},{init,eval_script,2,[]},{init,do_boot,3,[]}]})
```

Yes, the first part is missing for some reason. Not really sure why.

FWIW, it seems that Elixir has a similar issue, but when compiling instead of at runtime:
```
Compiling 2 files (.ex)
warning: redefining module Logger (current version loaded from /home/j3rn/.asdf/installs/elixir/1.13.4-otp-24/bin/../lib/logger/ebin/Elixir.Logger.beam)
  lib/logger.ex:1

Generated delete_me app
** (UndefinedFunctionError) function Logger.configure/1 is undefined or private
    (logger 1.13.4) Logger.configure([compile_time_application: nil])
    (mix 1.13.4) lib/mix/tasks/compile.all.ex:62: Mix.Tasks.Compile.All.with_logger_app/2
    (mix 1.13.4) lib/mix/tasks/compile.all.ex:36: Mix.Tasks.Compile.All.run/1
    (mix 1.13.4) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.13.4) lib/mix/tasks/compile.ex:131: Mix.Tasks.Compile.run/1
    (mix 1.13.4) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.13.4) lib/mix/cli.ex:84: Mix.CLI.run_task/2
{"init terminating in do_boot",{undef,[{'Elixir.Logger',flush,[],[]},{'Elixir.Kernel.CLI',run,1,[{file,"lib/kernel/cli.ex"},{line,59}]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({undef,[{Elixir.Logger,flush,[],[]},{Elixir.Kernel.CLI,run,1,[{_},{_}]},{init,start_em,1,[]},{init,do_boot,3,[]}]})

Crash dump is being written to: erl_crash.dump...done
```

Strangely, running `mix compile` a second time succeeds with no output. However, the `Logger` module defined within the project appears to be overridden by the built-in Logger at runtime.

Not sure what the best guidance is here other than "don't do that" :shrug:

**Comment by lpil** [comment]
What might we do here? It's come up a few times in Gleam (and I've seen people hit it in Elixir and Erlang commonly too), so it is something we would like to improve, but I'm not sure how exactly.

Perhaps we could make the Erlang compiler script check if the module is already defined, but we'd need make it so the script has access to all the already compiler modules.

**Comment by TanklesXL** [comment]
Is this the same as #1267?

**Comment by J3RN** [comment]
I believe the cause is the same, but the symptoms are different.

**Comment by lpil** [comment]
Well spotted, let's close this one in favour of that one
