### ISSUE TITLE
JavaScript: Constants should not be emitted before types

### ISSUE THREAD

**Issue by NicklasXYZ** [gleam-lang/gleam#1650]
Compiling the following Gleam code to JavaScript:
```gleam
// A type used to encapsulate all parameters used by the Permuted Congruential 
// Generator (PCG32).
type PermutedCongruentialGenerator {
  PermutedCongruentialGenerator(
    int_1: Int,
    int_18: Int,
    int_27: Int,
    int_59: Int,
    int_31: Int,
    multiplier: Int,
  )
}

// A constant containing the defualt PCG32 parameters
const pcg32 = PermutedCongruentialGenerator(
  int_1: 1,
  int_18: 18,
  int_27: 27,
  int_59: 59,
  int_31: 31,
  multiplier: 6364136223846793005,
)
```

Produces the something along the lines of following JavScript code:

```
import { CustomType } "../gleam.mjs";

const pcg32 = new PermutedCongruentialGenerator(
  1,
  18,
  27,
  59,
  31,
  6364136223846793005,
);

class PermutedCongruentialGenerator extends CustomType {
  constructor(int_1, int_18, int_27, int_59, int_31, multiplier) {
    super();
    this.int_1 = int_1;
    this.int_18 = int_18;
    this.int_27 = int_27;
    this.int_59 = int_59;
    this.int_31 = int_31;
    this.multiplier = multiplier;
  }
}
```
and results in the error (gleam v0.21, node v16.14):

```bash
$ gleam test --target javascript
  Compiling gleam_stats
   Compiled in 0.16s
    Running gleam_stats_test.main
file:///home/nicklasxyz/Desktop/gleam_stats/build/dev/javascript/gleam_stats/dist/gleam_stats/generators.mjs:11
const pcg32 = new PermutedCongruentialGenerator(
              ^

ReferenceError: Cannot access 'PermutedCongruentialGenerator' before initialization
    at file:///home/nicklasxyz/Desktop/gleam_stats/build/dev/javascript/gleam_stats/dist/gleam_stats/generators.mjs:11:15
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async main (file:///home/nicklasxyz/Desktop/gleam_stats/build/dev/javascript/gleeunit/dist/gleeunit_ffi.mjs:34:18)
```

**Comment by lpil** [comment]
Thank you
