### ISSUE TITLE
LSP crash on fresh project

### ISSUE THREAD

**Issue by timjs** [gleam-lang/gleam#1880]
Got multiple crashes of the LSP in VSCode; on existing projects, but also on a fresh project:

```
	compiler-cli/src/lsp.rs:730
	uri to module name
[Info  - 09:14:39] Connection to server got closed. Server will restart.
[Error - 09:14:39] Request textDocument/completion failed.
Error: Connection got disposed.
	at Object.dispose (/Users/tim/.vscode/extensions/gleam.gleam-2.0.0/out/extension.js:1:58393)
	at Object.dispose (/Users/tim/.vscode/extensions/gleam.gleam-2.0.0/out/extension.js:1:138476)
	at w.handleConnectionClosed (/Users/tim/.vscode/extensions/gleam.gleam-2.0.0/out/extension.js:1:138689)
	at w.handleConnectionClosed (/Users/tim/.vscode/extensions/gleam.gleam-2.0.0/out/extension.js:1:199035)
	at t (/Users/tim/.vscode/extensions/gleam.gleam-2.0.0/out/extension.js:1:136778)
	at r.invoke (/Users/tim/.vscode/extensions/gleam.gleam-2.0.0/out/extension.js:1:60006)
	at o.fire (/Users/tim/.vscode/extensions/gleam.gleam-2.0.0/out/extension.js:1:60767)
	at Y (/Users/tim/.vscode/extensions/gleam.gleam-2.0.0/out/extension.js:1:47651)
	at r.invoke (/Users/tim/.vscode/extensions/gleam.gleam-2.0.0/out/extension.js:1:60006)
	at o.fire (/Users/tim/.vscode/extensions/gleam.gleam-2.0.0/out/extension.js:1:60767)
	at f.fireClose (/Users/tim/.vscode/extensions/gleam.gleam-2.0.0/out/extension.js:1:72220)
	at Socket.<anonymous> (/Users/tim/.vscode/extensions/gleam.gleam-2.0.0/out/extension.js:1:73005)
	at Socket.emit (node:events:526:28)
	at Pipe.<anonymous> (node:net:687:12)
 INFO language_server_starting
 INFO gleam_project_detected
 INFO download_deps: locking_build_directory
 INFO download_deps: Reading manifest.toml
 INFO download_deps: manifest_up_to_date
 INFO sending Begin(WorkDoneProgressBegin { title: "Compiling Gleam", cancellable: Some(false), message: None, percentage: None })
 INFO locking_build_directory
 INFO loading_precompiled_package package=gleam_stdlib
 INFO loading_precompiled_package package=gleeunit
 INFO load{package=test_gleam_lsp}: Reading source files
 INFO compile{package=test_gleam_lsp}: Parsing source code
 INFO compile{package=test_gleam_lsp}: Type checking modules
 INFO compile{package=test_gleam_lsp}: Performing code generation
 INFO compile{package=test_gleam_lsp}: copying_native_source_files
 INFO compile{package=test_gleam_lsp}: skipping_erlang_bytecode_compilation
 INFO compile{package=test_gleam_lsp}: Writing package metadata to disc
 INFO sending End(WorkDoneProgressEnd { message: None })
error: Fatal compiler bug!
```

Versions I use:
```sh
> gleam --version
gleam 0.25.0
> code --version
1.73.1
6261075646f055b99068d3688932416f2346dd3b
arm64
```

Is this know to anybody else?

**Comment by lpil** [comment]
What OS are you using? Could you show the output with GLEAM_LOG=debug? Thank you

**Comment by timjs** [comment]
Sorry, forgot to include that! Running on macOS Ventura (13.0).

@lpil: How do I set that env variable so that VSCode uses it while executing the Gleam language extension? Running `code` from a shell with the variable set doesn't produce more detailed output in VSCode's "Output" terminal.

**Comment by lpil** [comment]
Honestly I've no idea how to operate vscode :(
