### ISSUE TITLE
Wrong error variant on panic in JS target

### ISSUE THREAD

**Issue by PgBiel** [gleam-lang/gleam#2906]
When using `panic` on JS, it is wrongly claimed that the error variant is `todo`:

```gleam
// src/amogcus.gleam 
import gleam/io

pub fn main() {
  panic as "OH NO"
  io.println("Hello from amogcus!")
}
```

```sh
$ gleam run -t js  
  Resolving versions
Downloading packages
 Downloaded 2 packages in 0.02s
  Compiling gleam_stdlib
  Compiling gleeunit
  Compiling amogcus
   Compiled in 0.04s
    Running amogcus.main
file:///tmp/amogcus/build/dev/javascript/prelude.mjs:345
  let error = new globalThis.Error(message);
              ^

Error: OH NO
    at makeError (file:///tmp/amogcus/build/dev/javascript/prelude.mjs:345:15)
    at main (file:///tmp/amogcus/build/dev/javascript/amogcus/amogcus.mjs:5:9)
    at file:///tmp/amogcus/build/dev/javascript/amogcus/gleam.main.mjs:2:1
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:106:12) {
  gleam_error: 'todo',   # <-------- here!
  module: 'amogcus',
  line: 4,
  fn: 'main'
}

Node.js v18.19.1
```

Seems like a mishap from the source code.

https://github.com/gleam-lang/gleam/blob/176334cd31dffd07c857db7a7066b6a032d5086f/compiler-core/src/javascript/expression.rs#L968

**Comment by lpil** [comment]
Oh no! Thank you
