### ISSUE TITLE
Case guard statement using constant from other module generates invalid JS code

### ISSUE THREAD

**Issue by nint8835** [gleam-lang/gleam#3043]
# Reproduction

Minimal repro repo, just run `gleam run`: https://github.com/nint8835/gleam_js_case_issue_repro

- Write a case statement using a guard referencing a constant from another module (ex. `x if x > other_module.example_const -> True`
- Compile the code for JavaScript and look at the output
- You will see that the reference to the other module takes the form of something like `$other_module/other_module.example_const`
- Attempting to run the code will result in either a division error or a reference error

# Versions

OS: macOS 14.4.1
Gleam version: 1.1.0, also tested with current code on `main`
Runtime: Node.js v20.11.1, also originally encountered with Firefox 125.0.2 (after bundling the code with Vite)

# Logs

<details>
  <summary>Expand for logs</summary>

```
❯ GLEAM_LOG=trace ../gleam/target/release/gleam run
DEBUG download_deps: locking_build_directory path="/Users/nint8835/Development/case_issue_repro/build/packages"
TRACE download_deps: reading_file path="/Users/nint8835/Development/case_issue_repro/gleam.toml"
DEBUG download_deps: reading_manifest_toml
TRACE download_deps: reading_file path="/Users/nint8835/Development/case_issue_repro/manifest.toml"
DEBUG download_deps: manifest_up_to_date
TRACE download_deps: reading_file path="/Users/nint8835/Development/case_issue_repro/build/packages/packages.toml"
DEBUG download_deps: locking_build_directory path="/Users/nint8835/Development/case_issue_repro/build/dev/erlang"
DEBUG download_deps: locking_build_directory path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript"
DEBUG download_deps: locking_build_directory path="/Users/nint8835/Development/case_issue_repro/build/prod/erlang"
DEBUG download_deps: locking_build_directory path="/Users/nint8835/Development/case_issue_repro/build/prod/javascript"
DEBUG download_deps: locking_build_directory path="/Users/nint8835/Development/case_issue_repro/build/lsp/erlang"
DEBUG download_deps: locking_build_directory path="/Users/nint8835/Development/case_issue_repro/build/lsp/javascript"
TRACE download_deps: writing_file path="/Users/nint8835/Development/case_issue_repro/build/packages/packages.toml"
TRACE reading_file path="/Users/nint8835/Development/case_issue_repro/gleam.toml"
TRACE reading_file path="/Users/nint8835/Development/case_issue_repro/gleam.toml"
TRACE reading_file path="/Users/nint8835/Development/case_issue_repro/gleam.toml"
 INFO Compiling packages
DEBUG locking_build_directory path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript"
TRACE reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_version"
TRACE reading_file path="/Users/nint8835/Development/case_issue_repro/build/packages/gleam_stdlib/gleam.toml"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@list.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@io.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@int.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@queue.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@string.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@bytes_builder.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@regex.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@string_builder.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@function.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@bool.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@uri.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@float.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@set.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@iterator.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@bit_array.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@option.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@pair.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@result.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@dict.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@order.cache_meta"
TRACE compile{package=gleam_stdlib}:load: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@dynamic.cache_meta"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/option
TRACE compile{package=gleam_stdlib}: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@option.cache"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/dict
TRACE compile{package=gleam_stdlib}: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@dict.cache"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/order
TRACE compile{package=gleam_stdlib}: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@order.cache"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/float
TRACE compile{package=gleam_stdlib}: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@float.cache"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/int
TRACE compile{package=gleam_stdlib}: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@int.cache"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/pair
TRACE compile{package=gleam_stdlib}: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@pair.cache"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/list
TRACE compile{package=gleam_stdlib}: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@list.cache"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/result
TRACE compile{package=gleam_stdlib}: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@result.cache"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/iterator
TRACE compile{package=gleam_stdlib}: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@iterator.cache"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/string_builder
TRACE compile{package=gleam_stdlib}: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@string_builder.cache"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/string
TRACE compile{package=gleam_stdlib}: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@string.cache"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/bit_array
TRACE compile{package=gleam_stdlib}: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@bit_array.cache"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/bool
TRACE compile{package=gleam_stdlib}: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@bool.cache"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/bytes_builder
TRACE compile{package=gleam_stdlib}: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@bytes_builder.cache"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/dynamic
TRACE compile{package=gleam_stdlib}: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@dynamic.cache"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/function
TRACE compile{package=gleam_stdlib}: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@function.cache"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/io
TRACE compile{package=gleam_stdlib}: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@io.cache"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/queue
TRACE compile{package=gleam_stdlib}: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@queue.cache"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/regex
TRACE compile{package=gleam_stdlib}: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@regex.cache"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/set
TRACE compile{package=gleam_stdlib}: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@set.cache"
DEBUG compile{package=gleam_stdlib}: module_to_load_from_cache module=gleam/uri
TRACE compile{package=gleam_stdlib}: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/_gleam_artefacts/gleam@uri.cache"
 INFO compile{package=gleam_stdlib}: analysing_modules count=0
DEBUG compile{package=gleam_stdlib}: performing_code_generation
TRACE compile{package=gleam_stdlib}: writing_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/gleam_stdlib/gleam.mjs"
DEBUG compile{package=gleam_stdlib}: copying_native_source_files
TRACE compile{package=gleam_stdlib}: reading_directory path="/Users/nint8835/Development/case_issue_repro/build/packages/gleam_stdlib/src"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/Users/nint8835/Development/case_issue_repro/build/packages/gleam_stdlib/src/gleam@list.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/Users/nint8835/Development/case_issue_repro/build/packages/gleam_stdlib/src/gleam@float.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/Users/nint8835/Development/case_issue_repro/build/packages/gleam_stdlib/src/gleam@queue.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/Users/nint8835/Development/case_issue_repro/build/packages/gleam_stdlib/src/dict.mjs"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/Users/nint8835/Development/case_issue_repro/build/packages/gleam_stdlib/src/gleam@iterator.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/Users/nint8835/Development/case_issue_repro/build/packages/gleam_stdlib/src/gleam@io.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/Users/nint8835/Development/case_issue_repro/build/packages/gleam_stdlib/src/gleam@dynamic.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/Users/nint8835/Development/case_issue_repro/build/packages/gleam_stdlib/src/gleam@string_builder.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/Users/nint8835/Development/case_issue_repro/build/packages/gleam_stdlib/src/gleam@bool.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/Users/nint8835/Development/case_issue_repro/build/packages/gleam_stdlib/src/gleam@bit_array.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/Users/nint8835/Development/case_issue_repro/build/packages/gleam_stdlib/src/gleam@option.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/Users/nint8835/Development/case_issue_repro/build/packages/gleam_stdlib/src/gleam@result.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/Users/nint8835/Development/case_issue_repro/build/packages/gleam_stdlib/src/gleam@pair.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/Users/nint8835/Development/case_issue_repro/build/packages/gleam_stdlib/src/gleam@order.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/Users/nint8835/Development/case_issue_repro/build/packages/gleam_stdlib/src/gleam@regex.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/Users/nint8835/Development/case_issue_repro/build/packages/gleam_stdlib/src/gleam@function.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/Users/nint8835/Development/case_issue_repro/build/packages/gleam_stdlib/src/gleam@int.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/Users/nint8835/Development/case_issue_repro/build/packages/gleam_stdlib/src/gleam@uri.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/Users/nint8835/Development/case_issue_repro/build/packages/gleam_stdlib/src/gleam@bytes_builder.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/Users/nint8835/Development/case_issue_repro/build/packages/gleam_stdlib/src/gleam@set.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/Users/nint8835/Development/case_issue_repro/build/packages/gleam_stdlib/src/gleam@string.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/Users/nint8835/Development/case_issue_repro/build/packages/gleam_stdlib/src/gleam@dict.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/Users/nint8835/Development/case_issue_repro/build/packages/gleam_stdlib/src/gleam_stdlib.erl"
DEBUG compile{package=gleam_stdlib}: skipping_unchanged_native_file_unchanged file="/Users/nint8835/Development/case_issue_repro/build/packages/gleam_stdlib/src/gleam_stdlib.mjs"
TRACE compile{package=case_issue_repro}:load: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/case_issue_repro/_gleam_artefacts/case_issue_repro.cache_meta"
TRACE compile{package=case_issue_repro}:load: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/case_issue_repro/_gleam_artefacts/other_module@other_module.cache_meta"
DEBUG compile{package=case_issue_repro}: module_to_load_from_cache module=other_module/other_module
TRACE compile{package=case_issue_repro}: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/case_issue_repro/_gleam_artefacts/other_module@other_module.cache"
DEBUG compile{package=case_issue_repro}: module_to_load_from_cache module=case_issue_repro
TRACE compile{package=case_issue_repro}: reading_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/case_issue_repro/_gleam_artefacts/case_issue_repro.cache"
 INFO compile{package=case_issue_repro}: analysing_modules count=0
DEBUG compile{package=case_issue_repro}: performing_code_generation
TRACE compile{package=case_issue_repro}: writing_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/case_issue_repro/gleam.mjs"
DEBUG compile{package=case_issue_repro}: copying_native_source_files
TRACE compile{package=case_issue_repro}: reading_directory path="/Users/nint8835/Development/case_issue_repro/src"
   Compiled in 0.01s
    Running case_issue_repro.main
TRACE writing_file path="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/case_issue_repro/gleam.main.mjs"
TRACE command_exec program="node" args="/Users/nint8835/Development/case_issue_repro/build/dev/javascript/case_issue_repro/gleam.main.mjs" env=[] cwd=None
file:///Users/nint8835/Development/case_issue_repro/build/dev/javascript/case_issue_repro/case_issue_repro.mjs:5
  if (example_val > ($other_module/other_module.example_const)) {
                                   ^

ReferenceError: other_module is not defined
    at main (file:///Users/nint8835/Development/case_issue_repro/build/dev/javascript/case_issue_repro/case_issue_repro.mjs:5:36)
    at file:///Users/nint8835/Development/case_issue_repro/build/dev/javascript/case_issue_repro/gleam.main.mjs:2:1
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.11.1
```

</details>

**Comment by lpil** [comment]
Oh dear! Thank you
