### ISSUE TITLE
Invalid JS generated when compiling a record that has a field named `constructor`, crashes at runtime

### ISSUE THREAD

**Issue by TanklesXL** [gleam-lang/gleam#3813]
The crash seems to be due to the call to `withFields` during a record update, as that function calls the constructor of the type

Reproduction: 
```gleam
pub type Thing {
  Thing(constructor: Nil)
}

pub fn main() {
  let a = Thing(constructor: Nil)
  let b = Thing(..a)
}
```

Resulting JS for type:
```js
export class Thing extends $CustomType {
  constructor(constructor) {
    super();
    this.constructor = constructor;
  }
}
```

Gleam version: 1.5.1

Crash:
```text
TypeError: this.constructor is not a constructor
    at Thing.withFields (file:///Users/rattard/code/gleam/constructor/build/dev/javascript/prelude.mjs:9:12)
    at main (file:///Users/rattard/code/gleam/constructor/build/dev/javascript/constructor/constructor.mjs:12:13)
    at file:///Users/rattard/code/gleam/constructor/build/dev/javascript/constructor/gleam.main.mjs:2:1
    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)

Node.js v23.1.0
```

**Comment by giacomocavalieri** [comment]
I'm working on this!

**Comment by joshi-monster** [comment]
My bad, I said on Discord that I was working on that. Should've commented on the issue as well.

**Comment by giacomocavalieri** [comment]
No worries! 💕
